language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  matrix:
  - REACT=16.4
  - REACT=16.5
  - REACT=16.6
  - REACT=16.8
sudo: false
install:
  - npm install
script:
  - npm run test
on:
  branch: master